---
title: "covid_data_exploration"
author: "Nora Ghenciulescu"
date: "2025-05-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())
library(lubridate)
library(segmented)
library(surveillance)
library(MASS)
library(nlme)

library(future)
library(future.apply)
plan("multisession")
options(mc.cores = 6)

library(nleqslv)
```

### Exploring model on their data

```{r}
bav = read_tsv("data/onset_age_group_bav.csv", show_col_types = FALSE)
bav

bav %>% group_by(date) %>% summarise(n=sum(onsets)) %>%
  filter(date<=ymd("2020-05-01"),
         date>=ymd("2020-02-15"))

bav
```
```{r}
bav_full = bav %>% group_by(date) %>%
  summarise(onsets=sum(onsets)) %>%
  right_join(tibble(date=seq(ymd("2020-02-24"), ymd("2020-05-15"), by = "1 day"))) %>%
  arrange(date) %>%
  mutate(onsets=replace_na(onsets,0))
```

```{r}
source("code/cp_fun.R")
cp_res_bav_full = perform_cp_analysis(data = bav_full,
                                      type = "both",
                                      cp_max_onset = 6,
                                      cp_max_backpro = 6,
                                      save_disc_optim_results = T,
                                      use_disc_optim_results = T,
                                      name_disc =  "bav_full")
```
```{r}
cp_res_bav_full
```
```{r}
cp_res_bav_full['bic_backpro']
```


```{r}
e <- new.env()
load("recreated_results/changepoint/discrete_optimization/backpro_disc_optim_bav_full.RData", envir = e)
# Now access it with:
backpro_discrete <- e$backpro_discrete

backpro_discrete
```

### Trying model on our data

```{r}
summary(data)
```


```{r}
data <- read_csv("age_group_data.csv", show_col_types = FALSE)

data_full = data %>% group_by(date) %>%
  summarise(onsets=sum(onsets)) %>%
  right_join(tibble(date=seq(ymd("2020-02-24"), ymd("2020-05-15"), by = "1 day"))) %>% ### change this to our start and end date
  arrange(date) %>%
  mutate(onsets=replace_na(onsets,0))

data_full
```


```{r}
cp_res_full = perform_cp_analysis(data = data_full,
                                      type = "both",
                                      cp_max_onset = 6,
                                      cp_max_backpro = 6,
                                      save_disc_optim_results = T,
                                      use_disc_optim_results = T,
                                      name_disc =  "bav_full")
cp_res_full
```
```{r}
cp_res_full['bic_backpro']
```

